### ISSUE TITLE
Checking if jobSpecs are still valid

### ISSUE THREAD

**Issue by onselakin** [compliance-framework/docs#5]
https://github.com/compliance-framework/website/blob/main/sequence_diagrams/CONFIGURATION_DIAGRAMS.md#:~:text=Because%20Users%20can%20cause%20a%20change%20to%20the%20job%20specs%2C

Since the assessments (and respectively jobs) require approval through some sort of mechanism at the configuration side (using the UI), we could implement versioning at the job level to manage this.

**Comment by gusfcarvalho** [comment]
If assessments are already granular for one specific component and one specific control, I agree with you. But then, how would we solve the whole "check that every VM on cloud is compliant to that single policy?".

My udnerstanding is that the Job Spec would cover this need, as there would be one assessment (for the policy) applicable to N VMs, - hence N Job Specs.

**Comment by gusfcarvalho** [comment]
Implementation Wise, Job Specs are a pivot table between Assessments and Components. Strictly speaking, we could also include `Controls` on that Pivot as we can have generic 'verify policy' assessment
