### ISSUE TITLE
JobRunner sequence diagram improvement

### ISSUE THREAD

**Issue by onselakin** [compliance-framework/docs#9]
https://github.com/compliance-framework/website/blob/main/sequence_diagrams/ASSESSMENT_RUNTIME_DIAGRAMS.md#jobrunner-workflow

Plugin download represents a separate flow. We need to distinguish it from the JobRunner sequence.

**Comment by gusfcarvalho** [comment]
Would you see it as part of the Job Manager instead? We only know which plugins to download on runtime, with a given configuration spec coming from the control plane

**Comment by onselakin** [comment]
Think of it as the `init` phase, where the runtime checks if the required attestation plugins are downloaded, ready, and configured. This process doesn't necessarily need to be done during the assessment runs, right? So we can move this process into its own sequence diagram.
